name: load_data
channels:
  - conda-forge
dependencies:
  - python=3.9
  - gdal=3.5.2
  - pycurl==7.45.1
  - geoserver-restconfig==2.0.8
  - psycopg2==2.9.3
  - seaborn==0.12.0
  - slack-sdk==3.21.3
  - boto3==1.28.32
